name: Codecov

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate CodeCov report
        uses: codecov/codecov-action@v1.0.7
        with:
          java-version: 1.8